<?php
    $labels = array();
    $labels['in'] = 'In';
    $labels['and'] = 'Und';
    $labels['or'] = 'Oder';
    $labels['not'] = 'Nicht';
    $labels['where'] = 'Wo';
    $labels['exclude'] = 'ausschließen';
    $labels['andsubfolders'] = 'mit Unterordnern';
    $labels['allfolders'] = 'Alle Ordner';
    $labels['SelectSavedSearches'] = 'Gespeicherte Suchanfragen';
    $labels['NoSearchSelected'] = 'Keine Suche gewählt';
    $labels['SaveThisSearch'] = 'Diese Suche speichern';
    $labels['SaveSearch'] = 'Speichern';
    $labels['NewSearch'] = 'Neue Suche';
    $labels['HasBeenSaved'] = 'Suche wurde gespeichert';

