<?php
    $labels = array();
    $labels['in'] = 'In';
    $labels['and'] = 'And';
    $labels['or'] = 'Or';
    $labels['not'] = 'Not';
    $labels['where'] = 'Where';
    $labels['exclude'] = 'Exclude';
    $labels['andsubfolders'] = 'and subfolders';
    $labels['allfolders'] = 'All Folders';
    $labels['SelectSavedSearches'] = 'Saved Searches';
    $labels['NoSearchSelected'] = 'No search selected';
    $labels['SaveThisSearch'] = 'Save this Search';
    $labels['SaveSearch'] = 'Save';
    $labels['NewSearch'] = 'New Search';
    $labels['HasBeenSaved'] = 'Search has been saved';

