<?php
    $labels = array();
    $labels['in'] = 'Dans';
    $labels['and'] = 'Et';
    $labels['or'] = 'Ou';
    $labels['not'] = 'Pas';
    $labels['where'] = 'Ou';
    $labels['exclude'] = 'Exclure';
    $labels['andsubfolders'] = 'et sous-dossiers';
    $labels['allfolders'] = 'Tous les dossiers';
    $labels['SelectSavedSearches'] = 'Saved Searches';
    $labels['NoSearchSelected'] = 'No search selected';
    $labels['SaveThisSearch'] = 'Save this Search';
    $labels['SaveSearch'] = 'Save';
    $labels['NewSearch'] = 'New Search';
    $labels['HasBeenSaved'] = 'Search has been saved';

